name: Flask CI

on:
  push:
    branches: [version_1_branch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Run linting
        run: |
          python -m pip install "tox<4.0"
          python -m tox -c ci_cd
      #   uses: github/super-linter@v4
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"

      - name: Run tests
        run: python -m pytest [...]

  configure-nginx:
    runs-on: ubuntu-latest
      steps:
        - name: Run Bash Script To Delpoy App
          env:
            EC2_HOST: ${{ secrets.EC2_HOST }}
            EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          run: |
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST << 'EOF'
              echo 'server{
                listen 80;
                server_name example.com

                location / {
                  proxy_pass http://localhost:3001;
                }
              }' | sudo tee /etc/nginx/sites-available/default
              sudo systemctl restart nginx
            EOF